service: express-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
