# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nectron
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: node-express
# "service" is the name of this project. This will also be added to your AWS resource names.
service: node-express-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: handler.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /
plugins:
  - serverless-offline
