version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      APP_KEYS: 'your_app_keys'
      API_TOKEN_SALT: 'your_api_token_salt'
      ADMIN_JWT_SECRET: 'your_admin_jwt_secret'
      JWT_SECRET: 'your_jwt_secret'
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    volumes:
      - ./strapi-app:/srv/app

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
